### ISSUE TITLE
Request for driver code that can actually be used with WLA-DX

### ISSUE THREAD

**Issue by thefloppydriver** [nathancassano/snesgss#9]
Could you make an example project or driver code that uses WLA-DX exclusively instead of WLA-DX+TCC? The use of TCC has made the code impossible to follow and limits all of your driver code to a *very* specific build environment which you haven't specified, essentially making sneslib.asm useless to the people who don't have whatever build environment you have.

**Comment by jeffythedragonslayer** [comment]
Where in the code are you getting tripped up?  Maybe I can help you.

**Comment by thefloppydriver** [comment]
@jeffythedragonslayer All of the TCC-generated variables.

**Comment by thefloppydriver** [comment]
There's isn't any documentation on how to use the provided functions in a game that runs on the SNES.

**Comment by jeffythedragonslayer** [comment]
Can you point me where exactly in the source?

**Comment by Ramsis-SNES** [comment]
@thefloppydriver Here you go:
[spc700-driver-v1.4-reassembly-labels.zip](https://github.com/nathancassano/snesgss/files/9244630/spc700-driver-v1.4-reassembly-labels.zip)

I completely disassembled the driver (latest version, don't worry about the "v1.4" in the filenames) back to "official" SPC700 syntax, then added original comments and labels back in. When assembled with WLA DX, it creates a byte-perfect copy of the driver portion found in `spc700.bin` upon exporting a completely empty song. :-)

It's not particularly useful as of yet, though, as the tracker software embeds quite a number of addresses into both `music_*.bin` and `spc700.bin`. This means we can't easily modify the driver, unless the size of the assembled driver code (2340 bytes) remains exactly the same.

The fact that

1. no relative addresses/references were used in music/sample data and
2. not even the smallest padding was used at the end (by 16-byte or better yet, 256-byte aligning the sample data) to allow for subsequent changes/enhancements of the driver code

means that in order to truly customize a SNESGSS implementation, you'd have to set up some ancient (and probably commercial) Borland build environment and get used to modifying and recompiling the tracker software to reflect whatever changes you make to the driver code. Or better yet, convert the whole project to Qt or whatever, and make it a cross-platform application, which it should have been in the first place.

Heh.

**Comment by thefloppydriver** [comment]
@Ramsis-SNES Thank you so much, this is perfect.

**Comment by Ramsis-SNES** [comment]
Glad I could help! :D

BTW, concerning modifying the driver, I stand corrected: There actually _exists_ padding at the end of the driver code (right before the `sampleDirAddr:` label), which I even duplicated in my WLA-SPC700 version of the driver linked above ... and then apparently completely forgot about. XD

Hmmm ... come to think of it, I probably should have put this part ...

```
.REPEAT 35					; 35 zeroes align the start of the following table to address $0B00 (in sound RAM) = $0902 (in driver .BIN file)
	.DB 0
.ENDR
```
... _before_ the `sampleDirAddr:` label, not after. Then, the `round()` might even be omitted in the `DSPInitData` table. I'll check and report back what I'll find.

Also, just today I discovered [this neat project](https://github.com/clbr/gsscli) where someone created a command-line based version of (a part of?) the SNESGSS software for exporting .GSM songs to SNES format. (I haven't tried it, but I think you still need the original Windows version of the software in order to create .GSM songs in the first place, though.)

**Comment by Ramsis-SNES** [comment]
Yeah, I messed up slightly. Here's the corrected .ASM file:
[spc700-driver-v1.4-reassembly-labels-fixed.zip](https://github.com/nathancassano/snesgss/files/9275829/spc700-driver-v1.4-reassembly-labels-fixed.zip)

Happy coding! :-)
